site_name: Hakuna Matata - Gino

repo_name: Hakuna Matata
repo_url: 'https://github.com/orgs/OrcestraGamificacao/teams/hakuna-matata/repositories'
copyright: 'Copyright &copy; 2021 Hakuna Matata'

site_dir: site

extra_css:
  - stylesheets/extra.css

theme:
  name: 'material'

  features:
    - navigation.tabs
  palette:
    - scheme: 'slate'
      primary: orange 
      accent: yellow

nav: 
  - Inicio: ./index.md
  - Documento de Arquitetura: ./architecture.md
  - Documento de Visão: ./vision.md
  - Politicas: 
    - Introdução: ./politics/goodHabits.md
    - Branch: ./politics/branchPolitics.md
    - Commit: ./politics/commitPolitics.md
    - Pull Request: ./politics/prPolitics.md
    - Issue: ./politics/issuePolitics.md